export const PROFESIONES_APS = [
  "MÉDICO",
  "ENFERMERA(O)",
  "MATRONA / MATRÓN",
  "KINESIÓLOGO(A)",
  "NUTRICIONISTA",
  "PSICÓLOGO(A)",
  "ODONTÓLOGO(A)",
  "TRABAJADOR(A) SOCIAL",
  "TERAPEUTA OCUPACIONAL",
  "FONOAUDIÓLOGO(A)",
  "QUÍMICO FARMACÉUTICO",
  "TENS",
  "ADMINISTRATIVO",
  "INGENIERO(A) / TI",
  "OTRO"
];
